Escape special characters before sending request to authnet
mglaman/authnet pull request #25
Opened 2018-01-17 18:48 UTC by subhojit777

2018-01-17 19:00 UTC, subhojit777 commented
Some history about this problem:

- https://secure.php.net/manual/en/simplexmlelement.addchild.php#112204

2018-01-17 20:21 UTC, mglaman requested changes

2018-01-17 20:21 UTC, mglaman commented on src/Request/XmlRequest.php
> +                $xml->{$key} = $value;
@subhojit777 it'd be great to have a test explaining this change. And even linking to that comment as to why we append children that way.

2018-01-23 14:32 UTC, subhojit777 commented
@mglaman I have added a test to backup my changes. Please check.

2018-01-23 16:12 UTC, mglaman approved these changes

2018-01-23 16:17 UTC, mglaman commented
@subhojit777 looks good. Will merge

2018-01-23 16:21 UTC, merged

2018-01-23 16:22 UTC, mglaman commented
Thanks a lot!